ignore duplicates route parsing from each middleware, and unfied methods
vijay4495/routes-list pull request #8
Opened 2020-08-02 23:02 UTC by ronyeh3

2020-08-02 23:03 UTC, ronyeh3 commented
fv

2020-08-03 18:56 UTC, NaveenDA commented
@ronyeh3 please run the `npm run format` and push the code again.

2020-08-03 18:56 UTC, NaveenDA requested changes

2020-08-03 18:56 UTC, NaveenDA commented on src/index.ts
> +            RoutesList.data[i].method = RoutesList.data[i].method.concat(item.method)
Please include the curly braces here.

2020-08-17 16:32 UTC, merged